local hunks = require('redline.hunks')

describe('hunks.ranges', function()
    it('parses a simple patch header', function()
        local r = hunks.ranges('@@ -10,5 +12,7 @@ context\n line\n')
        eq({ left = { { 10, 14 } }, right = { { 12, 18 } } }, r)
    end)

    it('defaults omitted counts to 1', function()
        local r = hunks.ranges('@@ -3 +4 @@\n')
        eq({ left = { { 3, 3 } }, right = { { 4, 4 } } }, r)
    end)

    it('handles multiple hunks and zero counts', function()
        local patch = '@@ -1,3 +1,4 @@\n a\n@@ -20,0 +25,2 @@\n b\n'
        local r = hunks.ranges(patch)
        eq({ left = { { 1, 3 } }, right = { { 1, 4 }, { 25, 26 } } }, r)
    end)
end)

describe('hunks.comment_in_hunks', function()
    local r = hunks.ranges('@@ -10,5 +12,7 @@\n')
    it('accepts a RIGHT line inside a hunk', function()
        eq(true, hunks.comment_in_hunks({ side = 'RIGHT', line = 18 }, r))
    end)
    it('rejects a RIGHT line outside all hunks', function()
        eq(false, hunks.comment_in_hunks({ side = 'RIGHT', line = 19 }, r))
    end)
    it('checks start_line of multi-line comments', function()
        eq(false, hunks.comment_in_hunks({ side = 'RIGHT', line = 14, start_line = 5 }, r))
        eq(true, hunks.comment_in_hunks({ side = 'RIGHT', line = 14, start_line = 12 }, r))
    end)
    it('uses the LEFT ranges for LEFT comments', function()
        eq(true, hunks.comment_in_hunks({ side = 'LEFT', line = 14 }, r))
        eq(false, hunks.comment_in_hunks({ side = 'LEFT', line = 15 }, r))
    end)
end)
